name: Build and Release

on:
  workflow_run:
    workflows: ["Semantic Release"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-binaries:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            target: 'aarch64-apple-darwin'
            args: '--bundles app,dmg'
          - platform: 'macos-latest'
            target: 'x86_64-apple-darwin'
            args: '--bundles app,dmg'
          - platform: 'ubuntu-22.04'
            target: 'x86_64-unknown-linux-gnu'
            args: '--bundles deb,appimage'
          - platform: 'windows-latest'
            target: 'x86_64-pc-windows-msvc'
            args: '--bundles msi,nsis'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Install macOS dependencies
        if: startsWith(matrix.platform, 'macos')
        run: |
          brew install create-dmg

      - name: Install frontend dependencies
        working-directory: app
        run: bun install --frozen-lockfile

      - name: Build Tauri app
        working-directory: app
        run: bun run tauri build --target ${{ matrix.target }} ${{ matrix.args }}

      - name: Upload macOS DMG
        if: startsWith(matrix.platform, 'macos')
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.target }}-dmg
          path: app/src-tauri/target/${{ matrix.target }}/release/bundle/dmg/*.dmg

      - name: Upload Windows MSI
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-msi
          path: app/src-tauri/target/${{ matrix.target }}/release/bundle/msi/*.msi

      - name: Upload Windows NSIS
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-nsis
          path: app/src-tauri/target/${{ matrix.target }}/release/bundle/nsis/*.exe

      - name: Upload Linux DEB
        if: matrix.platform == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: linux-deb
          path: app/src-tauri/target/${{ matrix.target }}/release/bundle/deb/*.deb

      - name: Upload Linux AppImage
        if: matrix.platform == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: linux-appimage
          path: app/src-tauri/target/${{ matrix.target }}/release/bundle/appimage/*.AppImage

  release:
    needs: build-binaries
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT
          else
            # Get the latest tag created by semantic-release
            LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
            echo "tag=${LATEST_TAG}" >> $GITHUB_OUTPUT
          fi

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure
        run: ls -R artifacts

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          files: |
            artifacts/**/*.dmg
            artifacts/**/*.msi
            artifacts/**/*.exe
            artifacts/**/*.deb
            artifacts/**/*.AppImage
          # Don't update release body or name since semantic-release already created it
          fail_on_unmatched_files: false